apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h3ipmdb0q-dotnet-basic
  janus-idp.io/tekton: h3ipmdb0q-dotnet-basic
  backstage.io/kubernetes-id: h3ipmdb0q-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h3ipmdb0q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
